version: '3.3'

services: 
    api:
        build: "."
        ports:
            - "5000:5000"
        restart: "always"
        networks: 
            - "api.network"
            
networks: 
    api.network: